### ISSUE TITLE
basic-tests fail with Nock

### ISSUE THREAD

**Issue by DanielGluskin** [testjavascript/integration-tests-a-z#35]
[basic-tests, "order failed, send mail to admin"](https://github.com/testjavascript/integration-tests-a-z/blob/06d8bed11e8f0da215264d55772ac0b86a3d831d/example-application/test/basic-tests.test.js#L94),

Is failing for me with: NetConnectNotAllowedError: Nock: Disallowed net connect for "mailer.com:443/send"

possible fix:
1. switch line 101 with: nock("https://mailer.com/").post(`/send`).reply(202);
2. use a stub instead of a spy at line 103.

**Comment by goldbergyoni** [comment]
@DanielGluskin Great catch.

Somehow, during back and fourth of code, these issues sneaked to our code. What you observed indeed doesn't make sense, no reason to have both nock and spy over the same collaborator. 

We're young and have no CI yet (@mikicho is working on that) so these things happen.

I fixed this in #38 and looking forward to hearing whether it worked for you (feel free to merge after approving)

p.s. We can't run different packages version since we have lock file. Also if you use nvm, then we lock Node version as well

@mikicho Maybe add to our contributing doc that one should run 'nvm use' before coding

**Comment by mikicho** [comment]
I'll add a small contribution file

**Comment by mikicho** [comment]
Isn't it closed by https://github.com/testjavascript/integration-tests-a-z/pull/38 ?

**Comment by goldbergyoni** [comment]
Sure it is
